sudo: false # faster builds
language: java
jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
env:
  global:
    - CODECOV_TOKEN="476c0221-3c1e-4082-82f4-071bb13b0fcd"

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=hippalus -Dsonar.login=75bb76351b1c244de27dce937eb1dbcc2475d619

after_success:
  - bash <(curl -s https://codecov.io/bash)